apiVersion: v1
kind: ConfigMap
metadata:
  name: fd-portal-config
  namespace: fd-portal
data:
  KEYSTONE_URL: "https://opole.minizon.net:5000/v3"
  USER_DOMAIN: "Default"
  HORIZON_URL: "https://opole.minizon.net/"
