apiVersion: apps/v1
kind: Deployment
metadata:
  name: fd-portal
  namespace: fd-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fd-portal
  template:
    metadata:
      labels:
        app: fd-portal
    spec:
      containers:
        - name: fd-portal
          image: tomtek/fd-portal:010
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: KEYSTONE_URL
              valueFrom:
                configMapKeyRef:
                  name: fd-portal-config
                  key: KEYSTONE_URL
            - name: USER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: fd-portal-config
                  key: USER_DOMAIN
            - name: HORIZON_URL
              valueFrom:
                configMapKeyRef:
                  name: fd-portal-config
                  key: HORIZON_URL
            - name: FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  name: fd-portal-secret
                  key: FLASK_SECRET
            - name: SKYLINE_URL
              valueFrom:
                configMapKeyRef:
                  name: fd-portal-config
                  key: SKYLINE_URL
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
