apiVersion: v1
kind: Secret
metadata:
  name: fd-portal-secret
  namespace: fd-portal
type: Opaque
stringData:
  # Replace this before deploying
  FLASK_SECRET: "HJAhM2y/v5vHRUmt7E4uBp3u+/jr4efSyGDWpHAC9nSszhB+Pf1b6V/4+hxmVW+6"
