apiVersion: v1
kind: Service
metadata:
  name: fd-portal
  namespace: fd-portal
  annotations:
    loadbalancer.openstack.org/load-balancer-address: "91.103.87.28"
spec:
  type: LoadBalancer
  selector:
    app: fd-portal
  ports:
    - name: https
      port: 443
      targetPort: 8000
      protocol: TCP

